# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php-5.6:
    docker:
      - image: circleci/php:5.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: deps
      - run: phpunit
  
  php-7.1:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: deps
      - run: phpunit

workflows:
  version: 2
  test:
    jobs:
      - php-5.6:
          filters:
            tags:
              only: /.*?/
      - php-7.1:
          filters:
            tags:
              only: /.*?/
